substitutions:
  name: "barcode-scanner"
  friendly_name: "Barcode Scanner"

  # Query ID for opentindb (https://opengtindb.org/api.php)
  rest_opentindb_queryid: "400000000"

  # I2C-Pins for the display
  display_i2c_sda: GPIO21
  display_i2c_scl: GPIO22

  # I2C-address for the OLED display
  ssd1306_i2c_address: "0x3C"

  # UART-Pins for the barcode scanner
  uart_tx_pin: GPIO09
  uart_rx_pin: GPIO10

  # Pin for the Buzzer/Beeper
  beeper_pin: GPIO16

packages:
  barcode: github://jhartlep/barcode-scanner/barcode.yaml@main
